# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_types_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='picbig',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
